# Playbook to configure and install Gitlab
---
- hosts: servers
  remote_user: root
  gather_facts: true
  become: true

  roles:
   - yum-update
   - { role: prerequisites_rhel6, when: 'ansible_distribution_major_version < "7"' }
   - { role: prerequisites_rhel7, when: 'ansible_distribution_major_version >= "7"' }
   - gitlab
   